### ISSUE TITLE
User can't use phrase "http whatever"

### ISSUE THREAD

**Issue by tomislater** [jimmyppi/searchcmd#2]
Here is the example:

```
╰─➤  ./Library/Python/2.7/bin/searchcmd python "http server"                                                                                                                                                   1 ↵
Traceback (most recent call last):
  File "./Library/Python/2.7/bin/searchcmd", line 9, in <module>
    load_entry_point('searchcmd==0.1.0', 'console_scripts', 'searchcmd')()
  File "/Users/tomek/Library/Python/2.7/lib/python/site-packages/searchcmd/__init__.py", line 77, in main
    commands = search(**search_args)
  File "/Users/tomek/Library/Python/2.7/lib/python/site-packages/searchcmd/__init__.py", line 144, in search
    urls = engine.get_hits(search_result)
  File "/Users/tomek/Library/Python/2.7/lib/python/site-packages/searchcmd/search_engines.py", line 85, in get_hits
    url = self.get_outgoing_url(link)
  File "/Users/tomek/Library/Python/2.7/lib/python/site-packages/searchcmd/search_engines.py", line 70, in get_outgoing_url
    u = Url(url)
  File "/Users/tomek/Library/Python/2.7/lib/python/site-packages/searchcmd/download.py", line 112, in __init__
    self.base_domain = tld.get_tld(self.url)
  File "/Users/tomek/Library/Python/2.7/lib/python/site-packages/tld/utils.py", line 172, in get_tld
    raise TldBadUrl(url=url)
tld.exceptions.TldBadUrl: Is not a valid URL http+server!
```

**Comment by tomislater** [comment]
Could I fix it, or are you working on it?

**Comment by jimmyppi** [comment]
Hi Tomek,

You are very welcome to fix it! It looks like `RE_URL_AS_PARAM` in `search_engines.py` is the problem.

**Comment by tomislater** [comment]
Okay, so I am going to fix it.
